version: "3.7"

services:

  app:
    image: ghcr.io/spadr/django_iot_core:main@sha256:27dc78040b11e91b68bcbcdb5878888a025ca741a48f3eed3da1ecc9f3e21180
    command: gunicorn iotproject.wsgi:application --bind 0.0.0.0:8000 --workers=2
    working_dir: /usr/src/app/
    volumes:
      #- ./app:/usr/src/app
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - front
      - back
  
  db:
    image: postgres:12.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    networks:
      - back
  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - 80:81
    depends_on:
      - app
    networks:
      - front
  
  mail:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025
    depends_on:
      - app
    networks:
      - front

volumes:
  db_data:
  static_volume:
  media_volume:

    
networks:
  front:
    external: false
  back:
    external: false
