# Generated by Django 3.1.6 on 2021-04-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IotModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('device', models.TextField()),
                ('time', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
    ]
