# Generated by Django 3.1.6 on 2021-07-17 09:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iotmodel',
            old_name='content',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='iotmodel',
            old_name='token',
            new_name='long_id',
        ),
        migrations.RemoveField(
            model_name='iotmodel',
            name='device',
        ),
        migrations.AddField(
            model_name='iotmodel',
            name='channel',
            field=models.CharField(default='japan', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iotmodel',
            name='name',
            field=models.CharField(default='japan', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iotmodel',
            name='type',
            field=models.CharField(default=datetime.datetime(2021, 7, 17, 9, 20, 57, 273423, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iotmodel',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
